//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maschinenbelegungsplanung {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Einstellungen : global::System.Configuration.ApplicationSettingsBase {
        
        private static Einstellungen defaultInstance = ((Einstellungen)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Einstellungen())));
        
        public static Einstellungen Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp")]
        public string Arbeitsverzeichnis {
            get {
                return ((string)(this["Arbeitsverzeichnis"]));
            }
            set {
                this["Arbeitsverzeichnis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\sem6\\ALO\\Maschinenbelegungsplanung\\lp_solve\\EXEC")]
        public string SolverPfad {
            get {
                return ((string)(this["SolverPfad"]));
            }
            set {
                this["SolverPfad"] = value;
            }
        }
    }
}
