//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlpkGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlpkGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brick_edit {
            get {
                object obj = ResourceManager.GetObject("brick_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the LP model!.
        /// </summary>
        internal static string correctWarning {
            get {
                return ResourceManager.GetString("correctWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlpKGui - LP Model Incorrect.
        /// </summary>
        internal static string correctWarningTitle {
            get {
                return ResourceManager.GetString("correctWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be double!.
        /// </summary>
        internal static string errorDouble {
            get {
                return ResourceManager.GetString("errorDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPS files (*.mps)|*.mps|Power-LP files (*.lpi)|*.lpi.
        /// </summary>
        internal static string fileFilter {
            get {
                return ResourceManager.GetString("fileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_page {
            get {
                object obj = ResourceManager.GetObject("folder_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon gnu48 {
            get {
                object obj = ResourceManager.GetObject("gnu48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate Interior Point  Solution.
        /// </summary>
        internal static string ipError {
            get {
                return ResourceManager.GetString("ipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate LP Solution!.
        /// </summary>
        internal static string lpError {
            get {
                return ResourceManager.GetString("lpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Simplex.
        /// </summary>
        internal static string methodDual {
            get {
                return ResourceManager.GetString("methodDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual; Primal.
        /// </summary>
        internal static string methodDualPrimal {
            get {
                return ResourceManager.GetString("methodDualPrimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primal Simplex.
        /// </summary>
        internal static string methodPrimal {
            get {
                return ResourceManager.GetString("methodPrimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate MIP Solution.
        /// </summary>
        internal static string mipError {
            get {
                return ResourceManager.GetString("mipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open file!.
        /// </summary>
        internal static string openError {
            get {
                return ResourceManager.GetString("openError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlpkGui - Open Error.
        /// </summary>
        internal static string openErrorTitle {
            get {
                return ResourceManager.GetString("openErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_add {
            get {
                object obj = ResourceManager.GetObject("page_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_go {
            get {
                object obj = ResourceManager.GetObject("page_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_save {
            get {
                object obj = ResourceManager.GetObject("page_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (Textbook).
        /// </summary>
        internal static string pricingStandard {
            get {
                return ResourceManager.GetString("pricingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Steepest Edge.
        /// </summary>
        internal static string pricingSteepest {
            get {
                return ResourceManager.GetString("pricingSteepest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save file!.
        /// </summary>
        internal static string saveError {
            get {
                return ResourceManager.GetString("saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlpkGui - Save Error.
        /// </summary>
        internal static string saveErrorTitle {
            get {
                return ResourceManager.GetString("saveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current LP model?.
        /// </summary>
        internal static string saveQuestion {
            get {
                return ResourceManager.GetString("saveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlpkGui - Save.
        /// </summary>
        internal static string saveQuestionTitle {
            get {
                return ResourceManager.GetString("saveQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate Bound Sensivity Information!.
        /// </summary>
        internal static string sensError {
            get {
                return ResourceManager.GetString("sensError", resourceCulture);
            }
        }
    }
}
