//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 01:41:25 PM CEST 
//


package webService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectiveFunctionValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element ref="{}resultRows" minOccurs="0"/>
 *         &lt;element ref="{}resultColumns"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objectiveFunctionValue",
    "resultRows",
    "resultColumns"
})
@XmlRootElement(name = "resultVariables")
public class ResultVariables {

    protected double objectiveFunctionValue;
    protected ResultRows resultRows;
    @XmlElement(required = true)
    protected ResultColumns resultColumns;

    /**
     * Gets the value of the objectiveFunctionValue property.
     * 
     */
    public double getObjectiveFunctionValue() {
        return objectiveFunctionValue;
    }

    /**
     * Sets the value of the objectiveFunctionValue property.
     * 
     */
    public void setObjectiveFunctionValue(double value) {
        this.objectiveFunctionValue = value;
    }

    /**
     * Gets the value of the resultRows property.
     * 
     * @return
     *     possible object is
     *     {@link ResultRows }
     *     
     */
    public ResultRows getResultRows() {
        return resultRows;
    }

    /**
     * Sets the value of the resultRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultRows }
     *     
     */
    public void setResultRows(ResultRows value) {
        this.resultRows = value;
    }

    /**
     * Gets the value of the resultColumns property.
     * 
     * @return
     *     possible object is
     *     {@link ResultColumns }
     *     
     */
    public ResultColumns getResultColumns() {
        return resultColumns;
    }

    /**
     * Sets the value of the resultColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultColumns }
     *     
     */
    public void setResultColumns(ResultColumns value) {
        this.resultColumns = value;
    }

}
