
package de.htwg_konstanz.tpsolver.web.solver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolverService", targetNamespace = "http://solver.web.tpsolver.htwg_konstanz.de/", wsdlLocation = "http://141.37.122.42:8180/SolverWebService/services/SolverService/?wsdl")
public class SolverService_Service
    extends Service
{

    private final static URL SOLVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOLVERSERVICE_EXCEPTION;
    private final static QName SOLVERSERVICE_QNAME = new QName("http://solver.web.tpsolver.htwg_konstanz.de/", "SolverService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://141.37.122.42:8180/SolverWebService/services/SolverService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOLVERSERVICE_WSDL_LOCATION = url;
        SOLVERSERVICE_EXCEPTION = e;
    }

    public SolverService_Service() {
        super(__getWsdlLocation(), SOLVERSERVICE_QNAME);
    }

    public SolverService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOLVERSERVICE_QNAME, features);
    }

    public SolverService_Service(URL wsdlLocation) {
        super(wsdlLocation, SOLVERSERVICE_QNAME);
    }

    public SolverService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOLVERSERVICE_QNAME, features);
    }

    public SolverService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolverService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SolverService
     */
    @WebEndpoint(name = "SolverServicePort")
    public SolverService getSolverServicePort() {
        return super.getPort(new QName("http://solver.web.tpsolver.htwg_konstanz.de/", "SolverServicePort"), SolverService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolverService
     */
    @WebEndpoint(name = "SolverServicePort")
    public SolverService getSolverServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://solver.web.tpsolver.htwg_konstanz.de/", "SolverServicePort"), SolverService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOLVERSERVICE_EXCEPTION!= null) {
            throw SOLVERSERVICE_EXCEPTION;
        }
        return SOLVERSERVICE_WSDL_LOCATION;
    }

}
