/*
 * Bernd Haertenstein
 * 
 * Copyright (c) 2011-2015 University of Applied Science Konstanz. All Rights Reserved.
 * 
 * Version 	1.0	WS10/11
 * Author	Bernd Haertenstein
 * 
 */
package jobshop;

import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ActionMap;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 * Shows the user in a separate dialog box the optimum of the lp-model.
 */
public class JobShopResultBox extends javax.swing.JDialog {
    private JButton closeButton;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;

    /* Create new user interface form to show the result. */
    public JobShopResultBox(java.awt.Frame parent, ResultList result) {
        super(parent);
        initComponents();
        createResultView(result);
    }

    @Action
    public void closeResultBox() {
        dispose();
    }

    private void createResultView(ResultList resultList) {
	/* Print line. */
		for (int i = 0; i < resultList.maxDauer + 1; i++) {
		    List<JTextField> innerList = new ArrayList<JTextField>();
		    /* Print column. */
		    for (int j = 0; j < resultList.anzM + 1; j++) {
		    	String name = "";
				GridBagConstraints c = new GridBagConstraints();
				c.gridx = i;
				c.gridy = j;
				c.fill = GridBagConstraints.BOTH;
				
				if (i == 0 || j == 0) {
				    if (i > 0 && j == 0) {
				    	name = "t" + i;
				    	} else if (i == 0 && j > 0) {
				    		name = "Maschine" + j;
				    	}
				    
				    JButton jButton = new JButton(name);
				    jButton.setName(name);
				    jButton.setFocusable(false);
				    jButton.validate();
				    jButton.setVisible(true);
				    jPanel2.add(jButton, c);
				} else {
				    JTextField jTField = new JTextField();
				    String value = "";
				    
				    for (Result res : resultList.result) {
				    	if (res.maschine == j && res.zeitpunkt == i) {
				    		value = "P" + res.produkt;
				    	}
				    }
				    
				    jTField.setText(value);
				    name = "jTFField_M" + j + "_Z" + i;
				    jTField.setName(name);
				    jTField.setEditable(false);
				    jTField.validate();
				    jTField.setVisible(true);
				    innerList.add(jTField);
				    jPanel2.add(jTField, c);
				}
		    }
		}
		
		/* Set bounds setBounds(int x,
         *            			 int y,
         *             			 int width,
                      			 int height) 
         */
		jPanel1.setBounds(-1, -1, -1, -1);
		jPanel2.setBounds(-1, -1, -1, -1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * 
     * Initialize the result box shown the user. The attributes of each variable can be be found at
     * package: jobshop.resources
     * file: JobShopResultBox.properties
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        closeButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ResourceMap resourceMap = Application.getInstance(JobShopApp.class).getContext().getResourceMap(JobShopResultBox.class);
        setTitle(resourceMap.getString("Form.title")); 
        setName("Form"); 

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); 
        jLabel1.setText(resourceMap.getString("jLabel1.text")); 
        jLabel1.setName("jLabel1"); 

        jScrollPane1.setName("jScrollPane1"); 

        jPanel1.setName("jPanel1"); 
        jPanel1.setLayout(new FlowLayout(FlowLayout.LEADING, 0, 0));

        jPanel2.setName("jPanel2");
        jPanel2.setLayout(new GridBagLayout());
        jPanel1.add(jPanel2);

        jScrollPane1.setViewportView(jPanel1);

        ActionMap actionMap = Application.getInstance(JobShopApp.class).getContext().getActionMap(JobShopResultBox.class, this);
        closeButton.setAction(actionMap.get("closeResultBox"));
        closeButton.setText(resourceMap.getString("closeButton.text")); 
        closeButton.setName("closeButton"); 

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(closeButton, Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }
}
