@echo off

::  Die benötigten Dateien werden nach c:\temp kopiert!
::


copy *.exe c:\temp\
copy *.xls c:\temp\
copy los.bat c:\temp\


echo.
echo --------------------------------------------------
echo.
echo Wechseln Sie nun in das Verzeichnis c:\temp und 
echo oeffnen Sie das Excel-Sheet Prototyp2.xls.
echo.
echo Weitere Infos sind im Methodenbank-GUI zu finden.
echo.
echo --------------------------------------------------
echo.

pause