/*
 * Bernd Haertenstein
 * 
 * Copyright (c) 2011-2015 University of Applied Science Konstanz. All Rights Reserved.
 * 
 * Version 	1.0	WS10/11
 * Author	Bernd Haertenstein
 * 
 */
package jobshop;

import java.awt.Font;
import javax.swing.ActionMap;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 * Show the user detailed information about JobShopNeu during runtime.
 */
public class JobShopAboutBox extends javax.swing.JDialog {
    private JButton closeButton;
    private JLabel jLabel1;
    private JLabel jLabel2;
   
    public JobShopAboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * 
     * Initialize the information (Impressum) box shown the user. The implementations of each variable can be be found at
     * package: jobshop.resources
     * file: JobShopAboutBox.properties
     */
    private void initComponents() {
        closeButton = new JButton();
        JLabel appTitleLabel = new JLabel();
		JLabel versionLabel = new JLabel();
		JLabel appVersionLabel = new JLabel();
		JLabel authorLabel = new JLabel();
		JLabel appAuthorLabel = new JLabel();
		JLabel releaseLabel = new JLabel();
		JLabel appReleaseLabel = new JLabel();
		JLabel appDescLabel = new JLabel();
		JLabel imageLabel = new JLabel();
	    jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ResourceMap resourceMap = Application.getInstance(JobShopApp.class).getContext().getResourceMap(JobShopAboutBox.class);
        setTitle(resourceMap.getString("title")); 
        setModal(true);
        setName("aboutBox"); 
        setResizable(false);

        ActionMap actionMap = Application.getInstance(JobShopApp.class).getContext().getActionMap(JobShopAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); 
        closeButton.setText(resourceMap.getString("closeButton.text")); 
        closeButton.setName("closeButton"); 

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | Font.BOLD, appTitleLabel.getFont().getSize()+4));
        appTitleLabel.setText(resourceMap.getString("Application.title")); 
        appTitleLabel.setName("appTitleLabel"); 

        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | Font.BOLD));
        versionLabel.setText(resourceMap.getString("versionLabel.text")); 
        versionLabel.setName("versionLabel"); 

        appVersionLabel.setText(resourceMap.getString("Application.version")); 
        appVersionLabel.setName("appVersionLabel"); 

        authorLabel.setFont(authorLabel.getFont().deriveFont(authorLabel.getFont().getStyle() | Font.BOLD));
        authorLabel.setText(resourceMap.getString("authorLabel.text"));
        authorLabel.setName("authorLabel"); 

        appAuthorLabel.setText(resourceMap.getString("Application.vendor")); 
        appAuthorLabel.setName("appAuthorLabel");

        releaseLabel.setFont(releaseLabel.getFont().deriveFont(releaseLabel.getFont().getStyle() | Font.BOLD));
        releaseLabel.setText(resourceMap.getString("releaseLabel.text"));
        releaseLabel.setName("releaseLabel"); 

        appReleaseLabel.setText(resourceMap.getString("Application.homepage")); 
        appReleaseLabel.setName("appReleaseLabel"); 

        appDescLabel.setText(resourceMap.getString("appDescLabel.text"));
        appDescLabel.setName("appDescLabel"); 

        imageLabel.setIcon(resourceMap.getIcon("imageLabel.icon")); 
        imageLabel.setName("imageLabel"); 

        jLabel1.setText(resourceMap.getString("jLabel1.text")); 
        jLabel1.setName("jLabel1"); 

        jLabel2.setText(resourceMap.getString("jLabel2.text")); 
        jLabel2.setName("jLabel2"); 

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addGroup(Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(versionLabel)
                            .addComponent(authorLabel)
                            .addComponent(releaseLabel))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(appVersionLabel)
                            .addComponent(appAuthorLabel)
                            .addComponent(appReleaseLabel)
                            .addComponent(jLabel1)))
                    .addComponent(appTitleLabel, Alignment.LEADING)
                    .addComponent(appDescLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(closeButton))
                .addContainerGap())
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 178, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitleLabel)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(appDescLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(appVersionLabel))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(appAuthorLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(releaseLabel)
                    .addComponent(appReleaseLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }
}
