NAME          Rezeptur
ROWS
 N  ZF
 L  VM1_1
 L  VM1_2
 L  VM1_3
 L  VM1_4
 L  VM1_5
 L  VM1_6
 L  VM1_7
 L  VM1_8
 L  VM1_9
 L  VM1_10
 L  VM1_11
 L  VM1_12
 L  VM1_13
 L  VM1_14
 L  VM1_15
 G  VM2_1
 G  VM2_2
 G  VM2_3
 G  VM2_4
 G  VM2_5
 G  VM2_6
 G  VM2_7
 G  VM2_8
 G  VM2_9
 G  VM2_10
 G  VM2_11
 G  VM2_12
 G  VM2_13
 G  VM2_14
 G  VM2_15
COLUMNS
    X11       ZF        0
    X11       VM1_1     1.0
    X11       VM2_1     1.0
    X11       BM1_1     1.0
    X11       BM2_1     1.0
    X12       ZF        0
    X12       VM1_1     1.0
    X12       VM2_1     1.0
    X12       BM1_2     1.0
    X12       BM2_2     1.0
    X13       ZF        0
    X13       VM1_1     1.0
    X13       VM2_1     1.0
    X13       BM1_3     1.0
    X13       BM2_3     1.0
    X14       ZF        0
    X14       VM1_1     1.0
    X14       VM2_1     1.0
    X14       BM1_4     1.0
    X14       BM2_4     1.0
    X21       ZF        0
    X21       VM1_2     1.0
    X21       VM2_2     1.0
    X21       BM1_1     1.0
    X21       BM2_1     1.0
    X22       ZF        0
    X22       VM1_2     1.0
    X22       VM2_2     1.0
    X22       BM1_2     1.0
    X22       BM2_2     1.0
    X23       ZF        0
    X23       VM1_2     1.0
    X23       VM2_2     1.0
    X23       BM1_3     1.0
    X23       BM2_3     1.0
    X24       ZF        0
    X24       VM1_2     1.0
    X24       VM2_2     1.0
    X24       BM1_4     1.0
    X24       BM2_4     1.0
    X31       ZF        0
    X31       VM1_3     1.0
    X31       VM2_3     1.0
    X31       BM1_1     1.0
    X31       BM2_1     1.0
    X32       ZF        0
    X32       VM1_3     1.0
    X32       VM2_3     1.0
    X32       BM1_2     1.0
    X32       BM2_2     1.0
    X33       ZF        0
    X33       VM1_3     1.0
    X33       VM2_3     1.0
    X33       BM1_3     1.0
    X33       BM2_3     1.0
    X34       ZF        0
    X34       VM1_3     1.0
    X34       VM2_3     1.0
    X34       BM1_4     1.0
    X34       BM2_4     1.0
    X41       ZF        0
    X41       VM1_4     1.0
    X41       VM2_4     1.0
    X41       BM1_1     1.0
    X41       BM2_1     1.0
    X42       ZF        0
    X42       VM1_4     1.0
    X42       VM2_4     1.0
    X42       BM1_2     1.0
    X42       BM2_2     1.0
    X43       ZF        0
    X43       VM1_4     1.0
    X43       VM2_4     1.0
    X43       BM1_3     1.0
    X43       BM2_3     1.0
    X44       ZF        0
    X44       VM1_4     1.0
    X44       VM2_4     1.0
    X44       BM1_4     1.0
    X44       BM2_4     1.0
    X51       ZF        0
    X51       VM1_5     1.0
    X51       VM2_5     1.0
    X51       BM1_1     1.0
    X51       BM2_1     1.0
    X52       ZF        0
    X52       VM1_5     1.0
    X52       VM2_5     1.0
    X52       BM1_2     1.0
    X52       BM2_2     1.0
    X53       ZF        0
    X53       VM1_5     1.0
    X53       VM2_5     1.0
    X53       BM1_3     1.0
    X53       BM2_3     1.0
    X54       ZF        0
    X54       VM1_5     1.0
    X54       VM2_5     1.0
    X54       BM1_4     1.0
    X54       BM2_4     1.0
    X61       ZF        0
    X61       VM1_6     1.0
    X61       VM2_6     1.0
    X61       BM1_1     1.0
    X61       BM2_1     1.0
    X62       ZF        0
    X62       VM1_6     1.0
    X62       VM2_6     1.0
    X62       BM1_2     1.0
    X62       BM2_2     1.0
    X63       ZF        0
    X63       VM1_6     1.0
    X63       VM2_6     1.0
    X63       BM1_3     1.0
    X63       BM2_3     1.0
    X64       ZF        0
    X64       VM1_6     1.0
    X64       VM2_6     1.0
    X64       BM1_4     1.0
    X64       BM2_4     1.0
    X71       ZF        0
    X71       VM1_7     1.0
    X71       VM2_7     1.0
    X71       BM1_1     1.0
    X71       BM2_1     1.0
    X72       ZF        0
    X72       VM1_7     1.0
    X72       VM2_7     1.0
    X72       BM1_2     1.0
    X72       BM2_2     1.0
    X73       ZF        0
    X73       VM1_7     1.0
    X73       VM2_7     1.0
    X73       BM1_3     1.0
    X73       BM2_3     1.0
    X74       ZF        0
    X74       VM1_7     1.0
    X74       VM2_7     1.0
    X74       BM1_4     1.0
    X74       BM2_4     1.0
    X81       ZF        0
    X81       VM1_8     1.0
    X81       VM2_8     1.0
    X81       BM1_1     1.0
    X81       BM2_1     1.0
    X82       ZF        0
    X82       VM1_8     1.0
    X82       VM2_8     1.0
    X82       BM1_2     1.0
    X82       BM2_2     1.0
    X83       ZF        0
    X83       VM1_8     1.0
    X83       VM2_8     1.0
    X83       BM1_3     1.0
    X83       BM2_3     1.0
    X84       ZF        0
    X84       VM1_8     1.0
    X84       VM2_8     1.0
    X84       BM1_4     1.0
    X84       BM2_4     1.0
    X91       ZF        0
    X91       VM1_9     1.0
    X91       VM2_9     1.0
    X91       BM1_1     1.0
    X91       BM2_1     1.0
    X92       ZF        0
    X92       VM1_9     1.0
    X92       VM2_9     1.0
    X92       BM1_2     1.0
    X92       BM2_2     1.0
    X93       ZF        0
    X93       VM1_9     1.0
    X93       VM2_9     1.0
    X93       BM1_3     1.0
    X93       BM2_3     1.0
    X94       ZF        0
    X94       VM1_9     1.0
    X94       VM2_9     1.0
    X94       BM1_4     1.0
    X94       BM2_4     1.0
    X101      ZF        0
    X101      VM1_10    1.0
    X101      VM2_10    1.0
    X101      BM1_1     1.0
    X101      BM2_1     1.0
    X102      ZF        0
    X102      VM1_10    1.0
    X102      VM2_10    1.0
    X102      BM1_2     1.0
    X102      BM2_2     1.0
    X103      ZF        0
    X103      VM1_10    1.0
    X103      VM2_10    1.0
    X103      BM1_3     1.0
    X103      BM2_3     1.0
    X104      ZF        0
    X104      VM1_10    1.0
    X104      VM2_10    1.0
    X104      BM1_4     1.0
    X104      BM2_4     1.0
    X111      ZF        0
    X111      VM1_11    1.0
    X111      VM2_11    1.0
    X111      BM1_1     1.0
    X111      BM2_1     1.0
    X112      ZF        0
    X112      VM1_11    1.0
    X112      VM2_11    1.0
    X112      BM1_2     1.0
    X112      BM2_2     1.0
    X113      ZF        0
    X113      VM1_11    1.0
    X113      VM2_11    1.0
    X113      BM1_3     1.0
    X113      BM2_3     1.0
    X114      ZF        0
    X114      VM1_11    1.0
    X114      VM2_11    1.0
    X114      BM1_4     1.0
    X114      BM2_4     1.0
    X121      ZF        0
    X121      VM1_12    1.0
    X121      VM2_12    1.0
    X121      BM1_1     1.0
    X121      BM2_1     1.0
    X122      ZF        0
    X122      VM1_12    1.0
    X122      VM2_12    1.0
    X122      BM1_2     1.0
    X122      BM2_2     1.0
    X123      ZF        0
    X123      VM1_12    1.0
    X123      VM2_12    1.0
    X123      BM1_3     1.0
    X123      BM2_3     1.0
    X124      ZF        0
    X124      VM1_12    1.0
    X124      VM2_12    1.0
    X124      BM1_4     1.0
    X124      BM2_4     1.0
    X131      ZF        0
    X131      VM1_13    1.0
    X131      VM2_13    1.0
    X131      BM1_1     1.0
    X131      BM2_1     1.0
    X132      ZF        0
    X132      VM1_13    1.0
    X132      VM2_13    1.0
    X132      BM1_2     1.0
    X132      BM2_2     1.0
    X133      ZF        0
    X133      VM1_13    1.0
    X133      VM2_13    1.0
    X133      BM1_3     1.0
    X133      BM2_3     1.0
    X134      ZF        0
    X134      VM1_13    1.0
    X134      VM2_13    1.0
    X134      BM1_4     1.0
    X134      BM2_4     1.0
    X141      ZF        0
    X141      VM1_14    1.0
    X141      VM2_14    1.0
    X141      BM1_1     1.0
    X141      BM2_1     1.0
    X142      ZF        0
    X142      VM1_14    1.0
    X142      VM2_14    1.0
    X142      BM1_2     1.0
    X142      BM2_2     1.0
    X143      ZF        0
    X143      VM1_14    1.0
    X143      VM2_14    1.0
    X143      BM1_3     1.0
    X143      BM2_3     1.0
    X144      ZF        0
    X144      VM1_14    1.0
    X144      VM2_14    1.0
    X144      BM1_4     1.0
    X144      BM2_4     1.0
    X151      ZF        0
    X151      VM1_15    1.0
    X151      VM2_15    1.0
    X151      BM1_1     1.0
    X151      BM2_1     1.0
    X152      ZF        0
    X152      VM1_15    1.0
    X152      VM2_15    1.0
    X152      BM1_2     1.0
    X152      BM2_2     1.0
    X153      ZF        0
    X153      VM1_15    1.0
    X153      VM2_15    1.0
    X153      BM1_3     1.0
    X153      BM2_3     1.0
    X154      ZF        0
    X154      VM1_15    1.0
    X154      VM2_15    1.0
    X154      BM1_4     1.0
    X154      BM2_4     1.0
RHS
    MYRHS     VM1_2     20
ENDATA
