//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 01:41:25 PM CEST 
//


package webService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}resultVariables" minOccurs="0"/>
 *         &lt;element ref="{}analysis" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="solver" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resultVariables",
    "analysis"
})
@XmlRootElement(name = "lpResult")
public class LpResult {

    protected ResultVariables resultVariables;
    protected Analysis analysis;
    @XmlAttribute(name = "solver")
    protected String solver;

    /**
     * Gets the value of the resultVariables property.
     * 
     * @return
     *     possible object is
     *     {@link ResultVariables }
     *     
     */
    public ResultVariables getResultVariables() {
        return resultVariables;
    }

    /**
     * Sets the value of the resultVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultVariables }
     *     
     */
    public void setResultVariables(ResultVariables value) {
        this.resultVariables = value;
    }

    /**
     * Gets the value of the analysis property.
     * 
     * @return
     *     possible object is
     *     {@link Analysis }
     *     
     */
    public Analysis getAnalysis() {
        return analysis;
    }

    /**
     * Sets the value of the analysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Analysis }
     *     
     */
    public void setAnalysis(Analysis value) {
        this.analysis = value;
    }

    /**
     * Gets the value of the solver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolver() {
        return solver;
    }

    /**
     * Sets the value of the solver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolver(String value) {
        this.solver = value;
    }

}
