//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 01:41:25 PM CEST 
//


package webService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rowName"/>
 *         &lt;element ref="{}rowType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rowName",
    "rowType"
})
@XmlRootElement(name = "row")
public class Row {

    @XmlElement(required = true)
    protected String rowName;
    @XmlElement(required = true)
    protected ComparatorCheck rowType;

    /**
     * Gets the value of the rowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowName() {
        return rowName;
    }

    /**
     * Sets the value of the rowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowName(String value) {
        this.rowName = value;
    }

    /**
     * Gets the value of the rowType property.
     * 
     * @return
     *     possible object is
     *     {@link ComparatorCheck }
     *     
     */
    public ComparatorCheck getRowType() {
        return rowType;
    }

    /**
     * Sets the value of the rowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparatorCheck }
     *     
     */
    public void setRowType(ComparatorCheck value) {
        this.rowType = value;
    }

}
