/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.ImageObserver;
import java.io.File;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

import serialize.DTOModell;
import serialize.SerializeModel;
import lpSolver.SolverPath;
import lpSolver.SolverPfad;
import facade.Facade;
import gui.Menue_Modellanlegen1;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.JMenuItem;

//Klasse wurde von den Studierenden erstellt

public class Hauptmenue extends javax.swing.JFrame {

	static boolean open = false;
	
    /**
     * Creates new form Hauptmenue
     */
    public Hauptmenue() {
    	super.setTitle("Umladeproblem 4.2");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        //-------------------------------------------------------------------------

        modellAnlegen = new javax.swing.JButton();
        dateiOeffnen = new javax.swing.JButton();
        beenden = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        checkBoxMigthy = new javax.swing.JCheckBoxMenuItem();
        checkBoxLPSolve = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
//      ActionListener wird als anonyme Klasse eingebunden
//        solverPfad.setText("Solver Pfad ");
//        solverPfad.addActionListener(new java.awt.event.ActionListener() {
//            // Beim Drücken des Menüpunktes wird actionPerformed aufgerufen
//            public void actionPerformed(java.awt.event.ActionEvent e) {
//                // Dateiauswahldialog wird erzeugt...
//                JFileChooser fc = new JFileChooser();
//                // ... und angezeigt
//                fc.showOpenDialog(null);
//            }
//        });
 
        // ActionListener wird als anonyme Klasse eingebunden
//        closeItem.addActionListener(new java.awt.event.ActionListener() {
//            // Beim Drücken des Menüpunktes wird actionPerformed aufgerufen
//            public void actionPerformed(java.awt.event.ActionEvent e) {
//                //Programm schließen
//                System.exit(0);
//            }
//        });
//    }

        
        //-------------------------------------------------------------------------

        
        modellAnlegen.setText("Modell anlegen");
        modellAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modellAnlegenActionPerformed(evt);
           }
        });

        dateiOeffnen.setText("Datei Öffnen");
        dateiOeffnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateiOeffnenActionPerformed(evt);
            }
        });

        beenden.setText("Beenden");
        beenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beendenActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("logo.png"))); // NOI18N

        menu.setText("Option");
     // macht das häkchen bei der Option  MightyMightyLp
        checkBoxMigthy.setSelected(false);
        checkBoxMigthy.setText("MightyMightyLp");
     // aktiviert die Option  MightyMightyLp
        checkBoxMigthy.setEnabled(false);
        menu.add(checkBoxMigthy);

        checkBoxLPSolve.setSelected(true);
    //    --------------------------------------------------------------------------------------------
        checkBoxLPSolve.setText("LP Solve");
    //   ----------------------------------------------------------------------    
        checkBoxLPSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        menu.add(checkBoxLPSolve);

        jMenuItem1.setText("Help");
        menu.add(jMenuItem1);
        
        
        jMenuItem1.addActionListener(new ActionListener(){
        	public void actionPerformed(ActionEvent arg0){
        			try {
			Desktop.getDesktop().open(new File("C:/Methodenbank/Methoden/Kategorie B/Umladeproblem 4.0/02 Dokumentation/Hilfe.pdf"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        		}
        	});
        
       

        jMenuItem2.setText("Info");
        menu.add(jMenuItem2);
        

        
        jMenuItem2.addActionListener(new ActionListener(){
             	public void actionPerformed(ActionEvent arg0){
             		Info info_window = new Info();
             		info_window.Info_method();
        }
        });
        
        
        jMenuBar1.add(menu);
        
        SolverPfadEinstellen = new JMenuItem("Solver Pfad einstellen");
        menu.add(SolverPfadEinstellen);
        
        SolverPfadEinstellen.addActionListener(new ActionListener(){
         	public void actionPerformed(ActionEvent arg0){
         	// JFileChooser-Objekt erstellen
                JFileChooser chooser = new JFileChooser("c:\\methodenbank\\solver\\lp_solve\\exec\\lp_solve.exe");
                // Dialog zum Oeffnen von Dateien anzeigen
                chooser.showOpenDialog(null);
                String solverPath;
				try {
					solverPath = chooser.getSelectedFile().toString();
	                System.out.println(solverPath);
				} catch (NullPointerException r) {
					// TODO Auto-generated catch block
					solverPath = "C:\\methodenbank\\solver\\lp_solve\\exec\\lp_solve.exe";
					System.out.println(solverPath);
				}
//                SolverPath.setLpSolvePath(solverPath);
                //Ausgabe des Solverpfades

    }
    });        

        setJMenuBar(jMenuBar1);
        
        final String solverPath;
        
//        JButton fileChooser = new JButton("Solver Pfad auswählen");
//        fileChooser.addActionListener(new ActionListener() {
//        	public void actionPerformed(ActionEvent e) {
//                // JFileChooser-Objekt erstellen
//                JFileChooser chooser = new JFileChooser("c:\\methodenbank\\solver\\lp_solve\\exec\\lp_solve.exe");
//                // Dialog zum Oeffnen von Dateien anzeigen
//                chooser.showOpenDialog(null);
//                String solverPath = chooser.getSelectedFile().toString();
////                SolverPath.setLpSolvePath(solverPath);
//                //Ausgabe des Solverpfades
//                System.out.println(solverPath);
//        	}
//        });
//        


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(modellAnlegen, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(dateiOeffnen, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(beenden, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        			.addGap(21))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(89)
        					.addComponent(modellAnlegen, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(dateiOeffnen, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(beenden, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(43)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(55, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//public javax.swing.JButton getSolverPfad() {
//		return solverPath;
//	}
//
//	public void setSolverPfad(javax.swing.JButton solverPfad) {
//		this.solverPfad = solverPfad;
//	}
//    ---------------------------------------------------------------------------
    
    private void modellAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modellAnlegenActionPerformed
        function_Modellanlegen();
    }//GEN-LAST:event_modellAnlegenActionPerformed

    private void dateiOeffnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateiOeffnenActionPerformed
    	open = true;
    	String path = "";
    	path = shwoOpenFile();
    	if(path != ""){
        	SerializeModel serializeModel = new SerializeModel();
        	DTOModell dto = serializeModel.unmarshallModell(path);
        	Modell modell = new Modell();
        	modell.gespeicherteTabellenAnzeigen(dto.getAnbieterArray(), dto.getNachfragerArray(), dto.getKostenmatrix());

    	}

    }//GEN-LAST:event_dateiOeffnenActionPerformed

    private void beendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beendenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_beendenActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
       
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hauptmenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hauptmenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hauptmenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hauptmenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hauptmenue().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beenden;
    private javax.swing.JButton dateiOeffnen;
    public javax.swing.JCheckBoxMenuItem checkBoxMigthy;
    public javax.swing.JCheckBoxMenuItem checkBoxLPSolve;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu menu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton modellAnlegen;
    private JMenuItem SolverPfadEinstellen;
    
    public void function_Pfadeingeben() {
    	SolverPfad pfadEingabe = new SolverPfad();
    	pfadEingabe.setVisible(true);
    }
  //-------------------------------------------------------------------------
    
    public void function_Modellanlegen() {

    	Menue_Modellanlegen1 knotenEingabe = new Menue_Modellanlegen1();
        knotenEingabe.setVisible(true);

    }
    
	public String shwoOpenFile(){
		
		String openPath = "";
		
		JFileChooser chooser = new JFileChooser("C:\\Methodenbank\\Methoden\\Kategorie B\\Umladeproblem4.2\\01 Programm\\Daten");
		chooser.setFileFilter(new FileFilter() {
			
			@Override
			public String getDescription() {
				return "xml";
			}
			
			@Override
			public boolean accept(File f) {
				return f.isDirectory() || f.getName().endsWith("xml");
			}
		});
		
		int result = chooser.showOpenDialog(this);
		
		if(result == JFileChooser.APPROVE_OPTION){
			
			openPath = chooser.getSelectedFile().toString();
		}
		
		return openPath;
		
	}
}
