package mischungsplaner;

/*
 * SolverPath.java
 *
 * Created on 22. Juni 2004, 23:02
 */
import constants.Constants;

import java.util.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import view.fileFilter.*;
import java.io.*;
/**
 *
 * @author  hmaass
 */
public class SolverPath extends javax.swing.JDialog {
    private Properties solverProperties;
    /** Creates new form SolverPath */
    public SolverPath(Properties solverProperties,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextField_LPSolvePfad.setText(solverProperties.getProperty("LP_PATH"));
        jTextField_LPSolverArbeitsverzeichnis.setText(solverProperties.getProperty("LP_WORKING_PATH"));
        jTextField_XAPath.setText(solverProperties.getProperty("XA_PATH"));
        this.setSize(Constants.PFADDIALOG_WIDTH, Constants.PFADDIALOG_HEIGHT);
        this.solverProperties = solverProperties;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton_Speichern = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_LPSolvePfad = new javax.swing.JTextField();
        jTextField_LPSolverArbeitsverzeichnis = new javax.swing.JTextField();
        jButton_LPSolvePfad = new javax.swing.JButton();
        jButton_LPSolveArbeitsverzeichnis = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jTextField_XAPath = new javax.swing.JTextField();
        jButton_XAPfad = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solver Pfade konfigurieren");
        jButton_Speichern.setText("Speichern");
        jButton_Speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SpeichernActionPerformed(evt);
            }
        });

        getContentPane().add(jButton_Speichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel1.setText("Pfad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Arbeitsverzeichnis");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("LP Solve");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

//        jLabel4.setText("XA");
//        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
//
//        jLabel5.setText("Pfad");
//        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jTextField_LPSolvePfad.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        jTextField_LPSolvePfad.setText("jTextField1");
        getContentPane().add(jTextField_LPSolvePfad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, 20));

        jTextField_LPSolverArbeitsverzeichnis.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
        jTextField_LPSolverArbeitsverzeichnis.setText("jTextField2");
        getContentPane().add(jTextField_LPSolverArbeitsverzeichnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 20));

        jButton_LPSolvePfad.setText("...");
        jButton_LPSolvePfad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LPSolvePfadActionPerformed(evt);
            }
        });

        getContentPane().add(jButton_LPSolvePfad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 40, 20));

        jButton_LPSolveArbeitsverzeichnis.setText("...");
        jButton_LPSolveArbeitsverzeichnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LPSolveArbeitsverzeichnisActionPerformed(evt);
            }
        });

        getContentPane().add(jButton_LPSolveArbeitsverzeichnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 40, 20));

        Cancel.setText("Abbrechen");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

//        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
//
//        jTextField_XAPath.setFont(new java.awt.Font("MS Sans Serif", 0, 10));
//        jTextField_XAPath.setText("jTextField2");
//        getContentPane().add(jTextField_XAPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 20));
//
//        jButton_XAPfad.setText("...");
//        jButton_XAPfad.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton_XAPfadActionPerformed(evt);
//            }
//        });
//
//        getContentPane().add(jButton_XAPfad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 40, 20));

//        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, 10));
//
//        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 440, 10));

        pack();
    }//GEN-END:initComponents

    private void jButton_XAPfadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XAPfadActionPerformed
                 JFileChooser chooser = new JFileChooser();;
         
        chooser.setFileFilter(new DirectoryFileFilter());
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            jTextField_XAPath.setText(chooser.getSelectedFile().toString());
        }   
    }//GEN-LAST:event_jButton_XAPfadActionPerformed

    private void jButton_LPSolveArbeitsverzeichnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LPSolveArbeitsverzeichnisActionPerformed
        JFileChooser chooser = new JFileChooser();;
         
        //chooser.setFileFilter(new DirectoryFileFilter());
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            jTextField_LPSolverArbeitsverzeichnis.setText(chooser.getSelectedFile().toString());
        }   
    }//GEN-LAST:event_jButton_LPSolveArbeitsverzeichnisActionPerformed

    private void jButton_LPSolvePfadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LPSolvePfadActionPerformed
         JFileChooser chooser = new JFileChooser();;
         
        chooser.setFileFilter(new DirectoryFileFilter());
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            jTextField_LPSolvePfad.setText(chooser.getSelectedFile().toString());
        }   
    }//GEN-LAST:event_jButton_LPSolvePfadActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void jButton_SpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SpeichernActionPerformed
        solverProperties.setProperty("LP_PATH", jTextField_LPSolvePfad.getText());
        solverProperties.setProperty("LP_WORKING_PATH", jTextField_LPSolverArbeitsverzeichnis.getText());
        solverProperties.setProperty("XA_PATH", jTextField_XAPath.getText());
        try {
            solverProperties.store(new FileOutputStream("solver.properties"), "Solver");
            this.setVisible(false);
        }catch (Exception e) {
             e.printStackTrace(System.err);
            JFrame hFrame = new JFrame("Warnung!");
            JLabel hLabel = new JLabel(Constants.ERROR_NO_COLUMN_SELECTED);
            hFrame.getContentPane().add(hLabel);
            hFrame.pack();
            hFrame.show();
        }
    }//GEN-LAST:event_jButton_SpeichernActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton jButton_LPSolveArbeitsverzeichnis;
    private javax.swing.JButton jButton_LPSolvePfad;
    private javax.swing.JButton jButton_Speichern;
    private javax.swing.JButton jButton_XAPfad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_LPSolvePfad;
    private javax.swing.JTextField jTextField_LPSolverArbeitsverzeichnis;
    private javax.swing.JTextField jTextField_XAPath;
    // End of variables declaration//GEN-END:variables
    
}
