DATUM                        03.11.84                                           
                                                                                
FABRIKEN                     (NAME, CODE)                                       
                                                                                
HAMBURG                      HH                                                 
BERLIN                       BE                                                 
FRANKFURT                    FM                                                 
MUENCHEN                     MU                                                 
SARBRUECKEN                  SA                                                 
                                                                                
ZENTRALLAEGER                (NAME, CODE, CAPAZITAET IN T/ZE)                   
                                                                                
HAMBURG                      HH        8500.00                                  
HANNOVER                     HA        12300.00                                 
FRANKFURT                    FM        15900.00                                 
MUENCHEN                     MU        10800.00                                 
SARBRUECKEN                  SA        9900.00                                  
                                                                                
ARTIKELSORTIMENT             (NAME, CODE, S(I) (1/ZE) T(I)  (DM/T/KM)           
MARGARINE                    MA        2.35      0.37                           
BUTTER                       BU        2.01      0.37                           
BRATFETT                     BF        1.89      0.21                           
SPEISEOEL                    OL        2.12      0.37                           
EISKREME                     EI        3.16      0.26                           
FERTIGGERICHT_1              F1        4.13      0.46                           
FERTIGGERICHT_2              F2        4.13      0.46                           
FERTIGGERICHT_3              F3        4.13      0.46                           
FERTIGGERICHT_4              F4        4.13      0.46                           
TIEFKUEHLKOST_1              T1        4.56      0.58                           
TIEFKUEHLKOST_2              T2        4.56      0.58                           
TIEFKUEHLKOST_3              T3        4.56      0.58                           
TIEFKUEHLKOST_4              T4        4.56      0.58                           
GETRAENKE_1                  G1        2.16      0.37                           
GETRAENKE_2                  G2        2.16      0.38                           
GETRAENKE_3                  G3        2.16      0.38                           
GETRAENKE_4                  G4        2.16      0.27                           
                                                                                
UMSCHLAGLAGER                (NAME, CODE)                                       
BERLIN                       BE                                                 
LUEBECK                      LB                                                 
SCHLESWIG                    SW                                                 
BIELEFELD                    BF                                                 
DUESSELDORF                  DD                                                 
KASSEL                       KA                                                 
WUERZBURG                    WB                                                 
REGENSBURG                   RE                                                 
ULM                          UL                                                 
BREMEN                       BR                                                 
AACHEN                       AA                                                 
SIEGEN                       SI                                                 
KONSTANZ                     KN                                                 
BAMBERG                      BB                                                 
KARLSRUHE                    KR                                                 
FREIBURG                     FB                                                 
TRIER                        TR                                                 
PRODUKTIONSDATEN             (FABRIK, ART.CODE, K(W,I) (T) H(W,I) (DM/T)        
HH                                                                              
                             MA        2000      323.67                         
                             BU        910       234.89                         
                             BF        580       189.67                         
                             OL        545       256.89                         
                             EI        967       656.67                         
                             T1        134       899.92                         
                             T2        234       768.23                         
                             T3        78        956.00                         
                             T4        89        943.78                         
                             F1        199       899.92                         
                             F2        234       768.23                         
                             F3        78        956.00                         
                             F4        222       867.21                         
                             G1        389       217.55                         
                             G2        288       316.77                         
                             G3        657       177.89                         
                             G4        456       234.33                         
BE                                                                              
                             MA        2000      123.67                         
                             BU        910       234.89                         
                             BF        580       189.67                         
                             OL        645       256.89                         
                             G1        389       217.55                         
                             G2        288       316.77                         
                             G3        657       177.89                         
                             G4        456       234.33                         
FM                                                                              
                             MA        2000      123.67                         
                             BU        910       234.89                         
                             BF        580       189.67                         
                             OL        445       256.89                         
                             EI        3568      567.67                         
                             T1        134       899.92                         
                             T2        234       768.23                         
                             T3        78        956.00                         
                             T4        89        943.78                         
                             F1        222       899.92                         
                             F2        234       768.23                         
                             F3        78        956.00                         
                             F4        189       943.78                         
                             G1        389       217.55                         
                             G2        288       316.77                         
                             G3        657       177.89                         
                             G4        456       234.33                         
MU                                                                              
                             MA        2000      123.67                         
                             BU        910       234.89                         
                             BF        580       189.67                         
                             OL        745       256.89                         
                             EI        913       587.67                         
                             T1        134       899.92                         
                             T2        234       768.23                         
                             T3        78        956.00                         
                             T4        290       943.78                         
                             F1        199       899.92                         
                             F2        234       768.23                         
                             F3        78        956.00                         
                             F4        176       943.78                         
                             G1        589       217.55                         
                             G2        688       316.77                         
                             G3        657       177.89                         
                             G4        856       234.33                         
SA                                                                              
                             EI        1472      589.67                         
                             T1        344       741.92                         
                             T2        434       668.23                         
                             T3        235       856.00                         
                             T4        189       843.78                         
                             F1        334       799.92                         
                             F2        334       668.23                         
                             F3        178       856.00                         
                             F4        289       843.78                         
                             G1        489       117.55                         
                             G2        388       256.77                         
                             G3        757       147.89                         
                             G4        556       189.33                         
BEDARFSDATEN                 (FUER JEDES U-L: ART.-CODE, BEDARF IN T)           
BE                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        37                                       
                             OL        111                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
LB                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        56                                       
                             OL        133                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
SW                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        34                                       
                             OL        141                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
BF                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        27                                       
                             OL        123                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
DD                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        32                                       
                             OL        145                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
KA                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        18                                       
                             OL        112                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
WB                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        26                                       
                             OL        118                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
RE                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        36                                       
                             OL        134                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
UL                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        21                                       
                             OL        127                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
BR                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        30                                       
                             OL        126                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
AA                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        29                                       
                             OL        145                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
SI                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        36                                       
                             OL        114                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
KN                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        38                                       
                             OL        122                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
BB                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        42                                       
                             OL        115                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
KR                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        11                                       
                             OL        133                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
FB                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        23                                       
                             OL        91                                       
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
TR                                                                              
                             MA        45                                       
                             BU        56                                       
                             BF        33                                       
                             OL        101                                      
                             EI        267                                      
                             T1        13                                       
                             T2        23                                       
                             T3        18                                       
                             T4        22                                       
                             F1        34                                       
                             F2        25                                       
                             F3        13                                       
                             F4        34                                       
                             G1        99                                       
                             G2        78                                       
                             G3        147                                      
                             G4        86                                       
ENTFERNUNGEN UL-ZL           (IN KM UMSCHLAGLAGER - ZENTRALLAGER                
BE                                                                              
                             HH        250                                      
                             HA        250                                      
                             FM        620                                      
                             MU        700                                      
                             SA        770                                      
LB                                                                              
                             HH        66                                       
                             HA        215                                      
                             FM        566                                      
                             MU        866                                      
                             SA        720                                      
SW                                                                              
                             HH        110                                      
                             HA        259                                      
                             FM        610                                      
                             MU        910                                      
                             SA        760                                      
BF                                                                              
                             HH        266                                      
                             HA        117                                      
                             FM        314                                      
                             MU        691                                      
                             SA        503                                      
DD                                                                              
                             HH        363                                      
                             HA        214                                      
                             FM        202                                      
                             MU        579                                      
                             SA        391                                      
KA                                                                              
                             HH        290                                      
                             HA        110                                      
                             FM        196                                      
                             MU        573                                      
                             SA        385                                      
WB                                                                              
                             HH        475                                      
                             HA        326                                      
                             FM        129                                      
                             MU        248                                      
                             SA        222                                      
RE                                                                              
                             HH        819                                      
                             HA        670                                      
                             FM        319                                      
                             MU        135                                      
                             SA        429                                      
UL                                                                              
                             HH        735                                      
                             HA        586                                      
                             FM        235                                      
                             MU        145                                      
                             SA        234                                      
BR                                                                              
                             HH        110                                      
                             HA        130                                      
                             FM        566                                      
                             MU        943                                      
                             SA        755                                      
AA                                                                              
                             HH        487                                      
                             HA        338                                      
                             FM        246                                      
                             MU        646                                      
                             SA        252                                      
SI                                                                              
                             HH        485                                      
                             HA        336                                      
                             FM        152                                      
                             MU        552                                      
                             SA        341                                      
KN                                                                              
                             HH        941                                      
                             HA        792                                      
                             FM        356                                      
                             MU        222                                      
                             SA        325                                      
BB                                                                              
                             HH        554                                      
                             HA        405                                      
                             FM        208                                      
                             MU        227                                      
                             SA        301                                      
KR                                                                              
                             HH        703                                      
                             HA        554                                      
                             FM        118                                      
                             MU        282                                      
                             SA        135                                      
FB                                                                              
                             HH        830                                      
                             HA        681                                      
                             FM        245                                      
                             MU        364                                      
                             SA        200                                      
TR                                                                              
                             HH        795                                      
                             HA        646                                      
                             FM        210                                      
                             MU        486                                      
                             SA        82                                       
ENTFERNUNGEN FB-ZL           (IN KM FABRIK - ZENTRALLAGER                       
HH                                                                              
                             HA        149                                      
                             FM        585                                      
                             MU        800                                      
                             SA        650                                      
BE                                                                              
                             HH        250                                      
                             HA        280                                      
                             FM        500                                      
                             MU        800                                      
                             SA        650                                      
FM                                                                              
                             HH        585                                      
                             HA        436                                      
                             MU        300                                      
                             SA        150                                      
MU                                                                              
                             HH        300                                      
                             HA        820                                      
                             FM        300                                      
                             SA        290                                      
SA                                                                              
                             HH        650                                      
                             HA        149                                      
                             FM        150                                      
                             MU        290                                      
ENDATA                                                                          
