{Types for CRT unit}

CONST
     { screen modes }
     BW40 = 0;
     CO40 = 1;
     C40  = CO40;
     BW80 = 2;
     CO80 = 3;
     C80  = CO80;
     MONO = 7;
     FONT8x8 = 256;
{Dark Colors: Foreground and Background}
     BLACK          = 0;
     BLUE           = 1;
     GREEN          = 2;
     CYAN           = 3;
     RED            = 4;
     MAGENTA        = 5;
     BROWN          = 6;
     LIGHTGRAY      = 7;
{Light Colors : Foreground only}
     DARKGRAY       = 8;
     LIGHTBLUE      = 9;
     LIGHTGREEN     = 10;
     LIGHTCYAN      = 11;
     LIGHTRED       = 12;
     LIGHTMAGENTA   = 13;
     YELLOW         = 14;
     WHITE          = 15;

     BLINK          = 128;



