//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 01:41:25 PM CEST 
//


package webService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="newLimit" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="newOptimum" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "newLimit",
    "newOptimum"
})
@XmlRootElement(name = "analysisUpperLimit")
public class AnalysisUpperLimit {

    @XmlElement(required = true)
    protected Object newLimit;
    @XmlElement(required = true)
    protected Object newOptimum;

    /**
     * Gets the value of the newLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNewLimit() {
        return newLimit;
    }

    /**
     * Sets the value of the newLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNewLimit(Object value) {
        this.newLimit = value;
    }

    /**
     * Gets the value of the newOptimum property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNewOptimum() {
        return newOptimum;
    }

    /**
     * Sets the value of the newOptimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNewOptimum(Object value) {
        this.newOptimum = value;
    }

}
