//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 01:41:25 PM CEST 
//


package webService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rowName"/>
 *         &lt;element ref="{}value"/>
 *         &lt;element ref="{}analysisUpperLimit"/>
 *         &lt;element ref="{}analysisLowerLimit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rowName",
    "value",
    "analysisUpperLimit",
    "analysisLowerLimit"
})
@XmlRootElement(name = "bVectorVariation")
public class BVectorVariation {

    @XmlElement(required = true)
    protected String rowName;
    protected double value;
    @XmlElement(required = true)
    protected AnalysisUpperLimit analysisUpperLimit;
    @XmlElement(required = true)
    protected AnalysisLowerLimit analysisLowerLimit;

    /**
     * Gets the value of the rowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowName() {
        return rowName;
    }

    /**
     * Sets the value of the rowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowName(String value) {
        this.rowName = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the analysisUpperLimit property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisUpperLimit }
     *     
     */
    public AnalysisUpperLimit getAnalysisUpperLimit() {
        return analysisUpperLimit;
    }

    /**
     * Sets the value of the analysisUpperLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisUpperLimit }
     *     
     */
    public void setAnalysisUpperLimit(AnalysisUpperLimit value) {
        this.analysisUpperLimit = value;
    }

    /**
     * Gets the value of the analysisLowerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisLowerLimit }
     *     
     */
    public AnalysisLowerLimit getAnalysisLowerLimit() {
        return analysisLowerLimit;
    }

    /**
     * Sets the value of the analysisLowerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisLowerLimit }
     *     
     */
    public void setAnalysisLowerLimit(AnalysisLowerLimit value) {
        this.analysisLowerLimit = value;
    }

}
