//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 01:41:25 PM CEST 
//


package webService;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}lpbaName"/>
 *         &lt;element ref="{}optimization"/>
 *         &lt;element ref="{}rows"/>
 *         &lt;element ref="{}columns"/>
 *         &lt;element ref="{}rightHandSides"/>
 *         &lt;element ref="{}properties" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lpbaName",
    "optimization",
    "rows",
    "columns",
    "rightHandSides",
    "properties"
})
@XmlRootElement(name = "lpba")
public class Lpba {

    @XmlElement(required = true)
    protected String lpbaName;
    @XmlElement(required = true)
    protected OptimizerCheck optimization;
    @XmlElement(required = true)
    protected Rows rows;
    @XmlElement(required = true)
    protected Columns columns;
    @XmlElement(required = true)
    protected RightHandSides rightHandSides;
    protected Properties properties;

    /**
     * Gets the value of the lpbaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLpbaName() {
        return lpbaName;
    }

    /**
     * Sets the value of the lpbaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLpbaName(String value) {
        this.lpbaName = value;
    }

    /**
     * Gets the value of the optimization property.
     * 
     * @return
     *     possible object is
     *     {@link OptimizerCheck }
     *     
     */
    public OptimizerCheck getOptimization() {
        return optimization;
    }

    /**
     * Sets the value of the optimization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptimizerCheck }
     *     
     */
    public void setOptimization(OptimizerCheck value) {
        this.optimization = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link Rows }
     *     
     */
    public Rows getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rows }
     *     
     */
    public void setRows(Rows value) {
        this.rows = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * @return
     *     possible object is
     *     {@link Columns }
     *     
     */
    public Columns getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Columns }
     *     
     */
    public void setColumns(Columns value) {
        this.columns = value;
    }

    /**
	 * Sets the value of the columns property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Columns }
	 *     
	 */
//	public void setColumns(Columns value) {
//	    this.columns = value;
//	}

	/**
     * Gets the value of the rightHandSides property.
     * 
     * @return
     *     possible object is
     *     {@link RightHandSides }
     *     
     */
    public RightHandSides getRightHandSides() {
        return rightHandSides;
    }

    /**
     * Sets the value of the rightHandSides property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightHandSides }
     *     
     */
    public void setRightHandSides(RightHandSides value) {
        this.rightHandSides = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

}
