VERSION 2.00
Begin Form Öffnen 
   Caption         =   "Datei öffnen"
   ClientHeight    =   1245
   ClientLeft      =   1560
   ClientTop       =   1515
   ClientWidth     =   5220
   Height          =   1650
   Left            =   1500
   LinkTopic       =   "Form1"
   ScaleHeight     =   1245
   ScaleWidth      =   5220
   Top             =   1170
   Width           =   5340
   Begin CommonDialog StdDialog1 
      Left            =   4560
      Top             =   720
   End
End
