#define Inhalt 1
#define Eine_Einf_hrung 2
#define Das_LP_Modell 3
#define Der_zweidimensionale_Zuschnitt 4
#define Eine_Einf_hrung_Werkstoffoptimierung 5
#define Das_LP_Modell_Werkstoffoptimierung 6
#define der_zweidimensionale_Werkstoffoptimierung 7
#define Das_Programm 8
#define Der_Hauptbildschirm 9
#define Men__Datei 10
#define Men__Optionen 11
#define Men__Fenster 12
#define Men__Hilfe 13
#define Das_Eingabefenster 14
#define Das_Variantenfenster 15
#define Das_Ausgabefenster 16
#define _ber_dieses_Programm 17
#define Bekannte_Fehler_und_m_gliche_Verbesserungen 18
